---
- name: Get k3s installed version
  ansible.builtin.command: k3s --version
  register: k3s_version_output
  changed_when: false
  ignore_errors: true

- name: Set k3s installed version
  when: not ansible_check_mode and k3s_version_output.rc == 0
  ansible.builtin.set_fact:
    installed_k3s_version: "{{ k3s_version_output.stdout_lines[0].split(' ')[2] }}"

# We should be downloading and installing the newer version only if we are in one of the following cases :
#   - we couldn't get k3s installed version in the first task of this role
#   - the installed version of K3s on the nodes is older than the requested version in ansible vars
- name: Download artifact only if needed
  when: not ansible_check_mode and ( k3s_version_output.rc != 0 or installed_k3s_version is version(k3s_installation_k3s_version, '<') )
  become: true
  block:
    - name: Download K3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io/
        timeout: 120
        dest: /usr/local/bin/k3s-install.sh
        owner: root
        group: root
        mode: "0755"

    - name: Download K3s binary
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-install.sh
      environment:
        INSTALL_K3S_SKIP_START: "true"
        INSTALL_K3S_VERSION: "{{ k3s_installation_k3s_version }}"
        INSTALL_K3S_EXEC: "agent"
      changed_when: true

- name: Delete any existing token from the environment if different from the new one
  become: true
  ansible.builtin.lineinfile:
    state: absent
    path: "{{ k3s_installation_systemd_dir }}/k3s-agent.service.env"
    regexp: "^K3S_TOKEN=\\s*(?!{{ k3s_installation_token }}\\s*$)"

- name: Add the token for joining the cluster to the environment
  become: true
  no_log: true # avoid logging the server token
  ansible.builtin.lineinfile:
    path: "{{ k3s_installation_systemd_dir }}/k3s-agent.service.env"
    line: "{{ item }}"
  with_items:
    - "K3S_TOKEN={{ k3s_installation_token }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Setup optional registry mirrors
  when: k3s_installation_registry_mirrors is defined and (k3s_installation_registry_mirrors | length > 0)
  block:
    - name: Make config directory
      ansible.builtin.file:
        path: "/etc/rancher/k3s"
        mode: "0755"
        state: directory

    - name: Add custom registry template
      ansible.builtin.template:
        src: "k3s-registries.yaml.j2"
        dest: "/etc/rancher/k3s/registries.yaml"
        owner: root
        group: root
        mode: "0644"
      notify: Restart k3s agent

- name: Copy K3s service file
  register: k3s_agent_service
  become: true
  ansible.builtin.template:
    src: "k3s-agent.service.j2"
    dest: "{{ k3s_installation_systemd_dir }}/k3s-agent.service"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Enable and check K3s service
  become: true
  ansible.builtin.systemd:
    name: k3s-agent
    daemon_reload: "{{ true if k3s_agent_service.changed else false }}"
    state: "{{ 'restarted' if k3s_agent_service.changed else 'started' }}"
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"
