---
- name: Restart k3s server
  ansible.builtin.systemd:
    name: k3s
    state: restarted
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart k3s agent
  ansible.builtin.systemd:
    name: k3s-agent
    state: restarted
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"
